version: "3"
services:

  anilibria.legacy:
    container_name: anilibria.legacy
    image: anilibria.legacy:$APP_VERSION
    restart: always
    volumes:
      - ./../../storage/media:/var/www/media/
    networks:
      - anilibria
    ports:
      - $DOCKER_EXTERNAL_PORT:80
    env_file:
      - .env

networks:
  anilibria:
    name: anilibria
